controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api

api_login:
    path: /api/auth/login
    methods: POST

api_logout:
    path: /api/auth/logout
    methods: POST